# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e321754a09f5e505cf63fd207d7e498871eb3da3e4f42b2fcdba3011fd72941267d5d531b413e3c307870d6fe4f152fb57d0fdc5c51eb9f9112433353e8a6785

test:
  secret_key_base: fc17023cedcafb70df79f235e4b244fe79adb912dc86b1507617948312d270631d078d9492967464fc44f716ecb28b915c81442ea603de6863c44e9fb45322a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
